language: node_js
sudo: false
cache:
  directories:
  - node_modules
dist: trusty
node_js:
- 7.3.0
branches:
  only:
  - master
env:
  global:
  - SELENIUM_HOST=hub-cloud.browserstack.com
  - SELENIUM_PORT=80
  - BS_AUTOMATE_PROJECT="$TRAVIS_REPO_SLUG"
  - BS_AUTOMATE_BUILD="Travis build No. $TRAVIS_BUILD_NUMBER for $TRAVIS_REPO_SLUG"
  - secure: ap0H0Y5hbJV59yyA4ok0q+0SiADIoRtJSyEP8LKaVcE0lUM+PY9GH3SXr5KlEqCzr2A6HpxcqHiFMTWc/zUZBnuRkvE2V31eRDH0yrw8boZOzaHCDnDINjC9tiKJS8X9lq+yLR/59xX472Qg6KwLxBhp1g93txFZWdrgumkfKlPzdJiYVyAws7reSr2nJLVtYZVLtJ2Spuh1seKNrAsWlCkO8sOEfTJyA+E8KuzXYoeNn1iCQQQ3qNiedsgfTQEHX1KxOSSOTLsLpLyJAruhs6nd3b/l21Yovrh4hu5pKHVdBKd15rXSQcklZvFAz1nEZ7nzr4x6OR5WJyHMX8nSsAHSIEkqZsrxs54FQXXvE4X1WA3cRNilckpN5qIp0G6t5PY2E81K5gkRkcoQ5JWdMh58Az1z/Zoj9yXkJS86Mt6X83DDdq00cJMaIRREkBjE2zMv18pAfFyIRGT8jgwOYVeJlT9Tze0g8Njo5IGjB7wJhkjpOLNyNrOc+KzJIsTZHVI4x/2W7REFmzkn5VpqrfAtxrDCNFIB8hqwhuVqQ2onhfFsGR6RGomcLdrkjUM6PA9nlZ7jQGoVqltOsmjOshqX1fbcYsV5y/SZaoTX7YawYGJZ0heNOqDgbgdbSv1e/2vnjeawXdIyguC2aDoFCQnvMDn+jYeQNVU1Ii+6QDg=
  - secure: ZwYCaVVyR1k1xMWGHxMwPVSvefvP4PN8Rna/vNZl5VIIlWT7GlYTSGDnEDEKbro3qKHAc+V3bNb+Z55pP77VVl9+HnYklBe7BO8QVeyY/KZWGUxlQwpsuvf6zX0G5PGd9Xk9twMh1uZwhTUCMqhbGpbG0mJvQ8IzVDz8k9CXxF65YLx+q3g3LIMEEWXZ5F1RL7WAHYVGZLZyTCrl+8zr2P89FXbdSf0kp626ZgXW9/NXamsq7ijjeU6cLiLCNB7BBAUICUyk8EsWMp8dcFvYhnIzufgolYIzcQKCEmzbIv/SlRrUQb+xsmMcfPpZcm7Ooq6O5lxs1vhg7kirmOSp5LZxXdjdNMugaIkq98rPhG6tfbtO7DxP6DUO98zhGh/X43mMWbm2PdzPtXR2NJgCv936UwIa7PeO8SK8e8Xt+BxAq+nQhC6PXAb35sAXR8hyl85HzQFqTrruG+jHXSX3V4jdmvwVEckjg8J4N5rt54dDaNm0U9IJ/aiVcWqMQiuz+Gf9CwzBEjs/7quqZykk6IAwlXilZaCIxbV+pLc7/nzbWx3630ki+Gz7SNFDlKUQ9L7HQfKc6SnQ9hbqaGQ7SDyMo368OA0iPXg1CWnkORGV+OIVXZTpRncTGBYLhgYImHywnMAtRdk7reXKhAXCtXx9FhPYKYg6cHxKf4msBEk=
before_script:
- wget http://oidamo.de/compact.tar
- mkdir -p src/assets/img/gallery/
- mv compact.tar src/assets/img/gallery/
- pushd src/assets/img/gallery/ && tar xvf compact.tar --strip-components 1 && popd
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
script:
- npm run browserstack-travis
after_success:
- node browserstack/setSessionStatus.js passed
after_failure:
- node browserstack/setSessionStatus.js failed
notifications:
  webhooks:
    on_success: always
    on_failure: always
    on_start: false
addons:
  browserstack:
    username: benjaminbrandmei2
    access_key:
      secure: W+ld0kWbD7eO4mrBxX6LqWVjLl94qv1hioLNoFN9TY/N1Pxu0yfsI/RxYhQa4ae/gOMpDTiE94xrMrRVDVC84VllEfr8xihB/fomZaidJhPD6T3L1vw3BZrOqca4Nc+ZbxVOZg/eiftPqy7upwblh3dtWariwXjX07QGf1B1+dl6PUMp7n5JCeou4UVncQqnodvVwZPxXjO86AcAXF+DaKftN/utEW1LxQysxhfpPWBBLY3iLRO6xKbQnrpyqE8gzFi2Idro3n9Pqaa8k3Tu7RbBZOxvHEuUQdnt4gMqnJuTrNb5vbOt5aL32dld7Y8qpoLerP4cVVXC4PMvVo6y1J8CSm/wwq2obeUSCRoyztpM9bAl3f+Go8HB/CjNOeBeNuDxq3wtkltwVZRWzGwOko7H/n3R8K7+Vx3jW8Wt4vxGznhbtMZLRsaXvaeXDh8NivAlEGbmIvi0Q7dmuTGtQdDriY7uPwbMDiBhP22RaKx/7Dg5HmfguMAj/2yQPtZ3l1iRZz0Ih8X+UqCcGxwamZGfRzkT5oxJ8AcquTws/UDH+g3hIaZ1vseztupdWnjprI1XwgjPfkQkd02M4pYlAzWLTdQ8W/gvisAa6Iz0T+zO64V9E7RmeH20pvfKVHjEzAGGuTeaqHLRnqS4RqlmRMxpG+QE6XeY0PkTSk/uUzQ=
